#!/usr/bin/env bash
# HRConnect Auto Pull Request Creator
# Creates GitHub PR after successful task completion

set -e

TASK_ID=$1
TITLE=$2
TASK_TYPE=$3
LOG_DIR=$4
BRANCH_PREFIX="task"

# Validation
if [ -z "$TASK_ID" ] || [ -z "$TITLE" ]; then
  echo "Usage: auto-pr.sh TASK_ID TITLE TASK_TYPE LOG_DIR"
  exit 1
fi

# GitHub config (from environment)
GITHUB_TOKEN=${GITHUB_TOKEN:-""}
GITHUB_OWNER=${GITHUB_REPO_OWNER:-""}
GITHUB_REPO=${GITHUB_REPO_NAME:-""}
PR_BASE_BRANCH=${GIT_BASE_BRANCH:-"main"}
PR_ASSIGNEE=${GITHUB_PR_ASSIGNEE:-""}

# If no GitHub config, skip PR creation
if [ -z "$GITHUB_TOKEN" ]; then
  echo "⚠️  GitHub token not configured - skipping PR creation"
  exit 0
fi

# Branch name
FEATURE_BRANCH="${BRANCH_PREFIX}/${TASK_ID}"

# PR title & body
PR_TITLE="feat: $TITLE"
PR_BODY="Generated by HRConnect autonomous development workflow.

**Task:** $TASK_ID  
**Type:** $TASK_TYPE  
**Agent:** $(echo $TASK_TYPE | tr '[:lower:]' '[:upper:]')

## Changes
Automated implementation of task: $TITLE

## Validation
✅ Unit tests passed  
✅ Integration tests passed  
✅ Linting clean  
✅ Build successful  

## Test Results
See logs: $LOG_DIR/$TASK_ID.log

---
*This PR was automatically created. Review before merging.*
"

# Create/switch to feature branch
git checkout -b "$FEATURE_BRANCH" 2>/dev/null || git checkout "$FEATURE_BRANCH"

# Push to remote
git push -u origin "$FEATURE_BRANCH" || {
  echo "Failed to push branch"
  exit 1
}

# Create PR using gh CLI if available
if command -v gh &> /dev/null; then
  gh pr create \
    --title "$PR_TITLE" \
    --body "$PR_BODY" \
    --base "$PR_BASE_BRANCH" \
    --head "$FEATURE_BRANCH" \
    --label "automated,feature,$TASK_TYPE" \
    ${PR_ASSIGNEE:+--assignee "$PR_ASSIGNEE"} && {
    echo "✅ PR created via gh CLI"
    exit 0
  }
fi

# Fallback: GitHub API
if [ -n "$GITHUB_OWNER" ] && [ -n "$GITHUB_REPO" ]; then
  curl -s -X POST \
    "https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/pulls" \
    -H "Authorization: token $GITHUB_TOKEN" \
    -H "Accept: application/vnd.github.v3+json" \
    -d "{\"title\":\"$PR_TITLE\",\"body\":\"$PR_BODY\",\"head\":\"$FEATURE_BRANCH\",\"base\":\"$PR_BASE_BRANCH\"}" && {
    echo "✅ PR created via GitHub API"
    exit 0
  }
fi

echo "⚠️  Could not create PR - gh CLI or GitHub config not available"
exit 0
