#!/usr/bin/env bash
# Quick start HRConnect autonomous development

PROJECT_DIR="/home/merger/hrconnect"
cd "$PROJECT_DIR"

echo "🎯 HRConnect Autonomous Development — Quick Start"
echo "================================================="
echo ""
echo "Step 1: Run one-time setup"
echo "  bash .hermes/setup.sh"
echo ""
echo "Step 2: Test manually (optional)"
echo "  bash .hermes/cron-dev-worker.sh"
echo ""
echo "Step 3: Monitor automation"
echo "  watch -n 30 'tail -30 .hermes/cron-logs/\$(date +%Y%m%d).log'"
echo ""
echo "Step 4: Check progress"
echo "  hermes cron list"
echo "  cat .hermes/metrics.json | jq '.metrics | to_entries[] | {key, value}'"
echo ""
echo "Step 5: View task queue"
echo "  cat .hermes/task-queue.json | jq '.queue[] | {id, priority, status}'"
echo ""
echo "Documentation:"
echo "  cat .hermes/README.md"
echo ""
