<?php

declare(strict_types=1);

$legacyInlineSvgFiles = [
    // Brand logo custom SVG (wajib raw — path brand, bukan Heroicon).
    'resources/views/components/application-logo.blade.php',
    'resources/views/components/application-mark.blade.php',
    'resources/views/components/app-logo-icon.blade.php',
    'resources/views/components/authentication-card-logo.blade.php',
    // Custom gauge chart (linearGradient + stroke-dasharray) — data-viz, bukan icon.
    'resources/views/livewire/admin/analytics-dashboard.blade.php',
];

$legacyWarningFindings = [
    ['app/Livewire/Admin/PayrollManager.php', 'hardcoded_ui_text', 112, 'Possible hardcoded Livewire UI text: "Payroll diajukan untuk verifikasi."'],
    ['app/Livewire/Admin/PayrollManager.php', 'hardcoded_ui_text', 122, 'Possible hardcoded Livewire UI text: "Payroll diverifikasi."'],
    ['app/Livewire/Admin/PayrollManager.php', 'hardcoded_ui_text', 132, 'Possible hardcoded Livewire UI text: "Payroll disetujui."'],
    ['app/Livewire/Forms/UserForm.php', 'hardcoded_ui_text', 219, 'Possible hardcoded Livewire UI text: "Demo user password cannot be changed."'],
    ['app/Livewire/User/MyPayslips.php', 'hardcoded_ui_text', 58, 'Possible hardcoded Livewire UI text: "Data karyawan tidak ditemukan."'],
    ['app/Livewire/User/MyPayslips.php', 'hardcoded_ui_text', 71, 'Possible hardcoded Livewire UI text: "Password payslip berhasil disimpan."'],
    ['lang/en.json', 'translation_file_drift', 1, 'Translation file drift detected: 194 key(s) exist in lang/id.json but not in lang/en.json. Blocking enforcement currently targets UI-used literal keys.'],
    ['resources/views/admin/attendances/report.blade.php', 'hardcoded_ui_text', 235, 'Possible hardcoded UI text: "Tidak ada data"'],
    ['resources/views/attendances/scan.blade.php', 'icon_only_button_accessibility', 41, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/auth/confirm-password.blade.php', 'icon_only_button_accessibility', 55, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/auth/forgot-password.blade.php', 'missing_form_label', 38, 'Possible missing label or aria-label for <input>.'],
    ['resources/views/auth/forgot-password.blade.php', 'icon_only_button_accessibility', 67, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/auth/login.blade.php', 'hardcoded_ui_text', 26, 'Possible hardcoded UI text: "Sistem HR & Payroll Terpadu"'],
    ['resources/views/auth/login.blade.php', 'hardcoded_ui_text', 31, 'Possible hardcoded UI text: "Kelola data karyawan, kehadiran, dan penggajian dengan alur kerja yang efisien dan tran..."'],
    ['resources/views/auth/login.blade.php', 'missing_form_label', 35, 'Possible missing label or aria-label for <input>.'],
    ['resources/views/auth/login.blade.php', 'hardcoded_ui_text', 39, 'Possible hardcoded UI text: "groups"'],
    ['resources/views/auth/login.blade.php', 'missing_form_label', 56, 'Possible missing label or aria-label for <input>.'],
    ['resources/views/auth/register.blade.php', 'icon_only_button_accessibility', 271, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/auth/reset-password.blade.php', 'missing_form_label', 40, 'Possible missing label or aria-label for <input>.'],
    ['resources/views/auth/reset-password.blade.php', 'missing_form_label', 59, 'Possible missing label or aria-label for <input>.'],
    ['resources/views/auth/reset-password.blade.php', 'icon_only_button_accessibility', 64, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/auth/reset-password.blade.php', 'missing_form_label', 78, 'Possible missing label or aria-label for <input>.'],
    ['resources/views/auth/two-factor-challenge.blade.php', 'icon_only_button_accessibility', 79, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/auth/verify-email.blade.php', 'icon_only_button_accessibility', 113, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/auth/verify-email.blade.php', 'icon_only_button_accessibility', 123, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/components/banner.blade.php', 'hardcoded_ui_text', 30, 'Possible hardcoded UI attribute text: "Dismiss"'],
    ['resources/views/components/branding/application-logo.blade.php', 'hardcoded_ui_text', 1, 'Possible hardcoded UI attribute text: "Logo"'],
    ['resources/views/components/branding/application-mark.blade.php', 'hardcoded_ui_text', 1, 'Possible hardcoded UI attribute text: "Logo"'],
    ['resources/views/components/branding/authentication-card-logo.blade.php', 'hardcoded_ui_text', 1, 'Possible hardcoded UI attribute text: "Logo"'],
    ['resources/views/components/button.blade.php', 'hardcoded_ui_text', 45, 'Possible hardcoded UI text: "progress_activity"'],
    ['resources/views/components/button.blade.php', 'hardcoded_ui_text', 58, 'Possible hardcoded UI text: "progress_activity"'],
    ['resources/views/components/checkbox.blade.php', 'missing_form_label', 1, 'Possible missing label or aria-label for <input>.'],
    ['resources/views/components/input.blade.php', 'missing_form_label', 3, 'Possible missing label or aria-label for <input>.'],
    ['resources/views/components/navigation/theme-toggle.blade.php', 'missing_form_label', 2, 'Possible missing label or aria-label for <input>.'],
    ['resources/views/components/pwa-install-prompt.blade.php', 'hardcoded_ui_text', 24, 'Possible hardcoded UI attribute text: "HRConnect"'],
    ['resources/views/components/shared/attendance-detail-modal.blade.php', 'hardcoded_ui_text', 107, 'Possible hardcoded UI attribute text: "Attachment"'],
    ['resources/views/components/textarea.blade.php', 'missing_form_label', 3, 'Possible missing label or aria-label for <textarea>.'],
    ['resources/views/components/user/home-actions-card.blade.php', 'icon_only_button_accessibility', 156, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/components/user/home-actions-card.blade.php', 'icon_only_button_accessibility', 67, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/components/user/location-card.blade.php', 'icon_only_button_accessibility', 23, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/components/user/scanner-card.blade.php', 'icon_only_button_accessibility', 14, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/components/user/tom-select-user.blade.php', 'missing_form_label', 148, 'Possible missing label or aria-label for <select>.'],
    ['resources/views/documents/employee-template.blade.php', 'hardcoded_ui_text', 6, 'Possible hardcoded UI text: "Document"'],
    ['resources/views/knowledge-base/index.blade.php', 'missing_form_label', 30, 'Possible missing label or aria-label for <input>.'],
    ['resources/views/layouts/guest.blade.php', 'hardcoded_ui_text', 61, 'Possible hardcoded UI text: "ID"'],
    ['resources/views/layouts/guest.blade.php', 'hardcoded_ui_text', 62, 'Possible hardcoded UI text: "EN"'],
    ['resources/views/livewire/admin/activity-logs.blade.php', 'mobile_layout_red_flag', 102, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/activity-logs.blade.php', 'mobile_layout_red_flag', 90, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/announcement-manager.blade.php', 'mobile_layout_red_flag', 63, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/appraisal-manager.blade.php', 'mobile_layout_red_flag', 100, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/appraisal-manager.blade.php', 'hardcoded_ui_text', 493, 'Possible hardcoded UI attribute text: "https://meet.google.com/..."'],
    ['resources/views/livewire/admin/appraisal-manager.blade.php', 'hardcoded_ui_text', 502, 'Possible hardcoded UI attribute text: "https://meet.google.com/..."'],
    ['resources/views/livewire/admin/appraisal-manager.blade.php', 'mobile_layout_red_flag', 64, 'High default grid column count may be too dense for mobile.'],
    ['resources/views/livewire/admin/appraisal-manager.blade.php', 'mobile_layout_red_flag', 66, 'High default grid column count may be too dense for mobile.'],
    ['resources/views/livewire/admin/appraisal-manager.blade.php', 'mobile_layout_red_flag', 98, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/dashboard.blade.php', 'mobile_layout_red_flag', 672, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/dashboard.blade.php', 'mobile_layout_red_flag', 819, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/employee-create.blade.php', 'hardcoded_ui_text', 158, 'Possible hardcoded UI attribute text: "e.g. 5.000.000"'],
    ['resources/views/livewire/admin/employee-document-request-manager.blade.php', 'mobile_layout_red_flag', 36, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/employee-edit.blade.php', 'hardcoded_ui_text', 158, 'Possible hardcoded UI attribute text: "e.g. 5.000.000"'],
    ['resources/views/livewire/admin/employees.blade.php', 'mobile_layout_red_flag', 101, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/employees.blade.php', 'hardcoded_ui_text', 524, 'Possible hardcoded UI attribute text: "e.g. 5.000.000"'],
    ['resources/views/livewire/admin/employees.blade.php', 'hardcoded_ui_text', 542, 'Possible hardcoded UI attribute text: "e.g. 5.000.000"'],
    ['resources/views/livewire/admin/employees.blade.php', 'hardcoded_ui_text', 545, 'Possible hardcoded UI attribute text: "e.g. 25.000"'],
    ['resources/views/livewire/admin/employees.blade.php', 'hardcoded_ui_text', 735, 'Possible hardcoded UI attribute text: "e.g. 5.000.000"'],
    ['resources/views/livewire/admin/employees.blade.php', 'hardcoded_ui_text', 777, 'Possible hardcoded UI attribute text: "e.g. 5.000.000"'],
    ['resources/views/livewire/admin/holiday-manager.blade.php', 'mobile_layout_red_flag', 48, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/import-export/attendance.blade.php', 'icon_only_button_accessibility', 143, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/admin/import-export/attendance.blade.php', 'icon_only_button_accessibility', 28, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/admin/import-export/attendance.blade.php', 'mobile_layout_red_flag', 425, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/import-export/attendance.blade.php', 'icon_only_button_accessibility', 46, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/admin/import-export/user.blade.php', 'icon_only_button_accessibility', 28, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/admin/import-export/user.blade.php', 'mobile_layout_red_flag', 364, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/import-export/user.blade.php', 'icon_only_button_accessibility', 46, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/admin/knowledge-base-manager.blade.php', 'hardcoded_ui_text', 211, 'Possible hardcoded UI text: "Format: PDF, maksimal 10 MB"'],
    ['resources/views/livewire/admin/knowledge-base-manager.blade.php', 'mobile_layout_red_flag', 53, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/leave-approval.blade.php', 'mobile_layout_red_flag', 48, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/master-data/admin.blade.php', 'mobile_layout_red_flag', 150, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/master-data/division.blade.php', 'mobile_layout_red_flag', 53, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/master-data/education.blade.php', 'mobile_layout_red_flag', 54, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/master-data/job-title.blade.php', 'mobile_layout_red_flag', 70, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/master-data/leave-types.blade.php', 'mobile_layout_red_flag', 37, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/master-data/shift.blade.php', 'mobile_layout_red_flag', 77, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/payroll-manager.blade.php', 'missing_form_label', 282, 'Possible missing label or aria-label for <textarea>.'],
    ['resources/views/livewire/admin/payroll-manager.blade.php', 'hardcoded_ui_text', 22, 'Possible hardcoded UI text: "Semua"'],
    ['resources/views/livewire/admin/payroll-manager.blade.php', 'hardcoded_ui_text', 48, 'Possible hardcoded UI text: "Total Payroll"'],
    ['resources/views/livewire/admin/payroll-manager.blade.php', 'hardcoded_ui_text', 50, 'Possible hardcoded UI text: "Semua status & filter"'],
    ['resources/views/livewire/admin/payroll-manager.blade.php', 'mobile_layout_red_flag', 87, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/payroll-manager.blade.php', 'mobile_layout_red_flag', 99, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/payroll-settings.blade.php', 'hardcoded_ui_text', 219, 'Possible hardcoded UI text: "Rp"'],
    ['resources/views/livewire/admin/payroll-settings.blade.php', 'mobile_layout_red_flag', 60, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/profile/activity-log-viewer.blade.php', 'mobile_layout_red_flag', 17, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/reimbursement-manager.blade.php', 'mobile_layout_red_flag', 30, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/schedule-component.blade.php', 'mobile_layout_red_flag', 34, 'High default grid column count may be too dense for mobile.'],
    ['resources/views/livewire/admin/schedule-component.blade.php', 'mobile_layout_red_flag', 44, 'High default grid column count may be too dense for mobile.'],
    ['resources/views/livewire/admin/settings.blade.php', 'icon_only_button_accessibility', 120, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/shared/finance/cash-advance-manager-content.blade.php', 'mobile_layout_red_flag', 231, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/shared/finance/cash-advance-manager-content.blade.php', 'mobile_layout_red_flag', 27, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/shared/notifications-dropdown.blade.php', 'icon_only_button_accessibility', 5, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/attendance-correction-page.blade.php', 'icon_only_button_accessibility', 16, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/attendance-correction-page.blade.php', 'mobile_layout_red_flag', 54, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/attendance-history.blade.php', 'hardcoded_ui_text', 123, 'Possible hardcoded UI text: "H"'],
    ['resources/views/livewire/user/attendance-history.blade.php', 'mobile_layout_red_flag', 36, 'High default grid column count may be too dense for mobile.'],
    ['resources/views/livewire/user/attendance-history.blade.php', 'mobile_layout_red_flag', 45, 'High default grid column count may be too dense for mobile.'],
    ['resources/views/livewire/user/clock-in-action.blade.php', 'icon_only_button_accessibility', 188, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/clock-in-action.blade.php', 'icon_only_button_accessibility', 32, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/clock-in-action.blade.php', 'icon_only_button_accessibility', 56, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/employee-document-request-page.blade.php', 'icon_only_button_accessibility', 15, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/face-enrollment.blade.php', 'icon_only_button_accessibility', 26, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/face-enrollment.blade.php', 'icon_only_button_accessibility', 33, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/face-enrollment.blade.php', 'icon_only_button_accessibility', 40, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/finance/my-cash-advances.blade.php', 'icon_only_button_accessibility', 14, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/finance/my-cash-advances.blade.php', 'hardcoded_ui_text', 188, 'Possible hardcoded UI text: "Rp"'],
    ['resources/views/livewire/user/finance/my-cash-advances.blade.php', 'icon_only_button_accessibility', 25, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/finance/my-cash-advances.blade.php', 'hardcoded_ui_text', 50, 'Possible hardcoded UI text: "Rp"'],
    ['resources/views/livewire/user/home-attendance-status.blade.php', 'icon_only_button_accessibility', 61, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/knowledge-base-chat.blade.php', 'missing_form_label', 109, 'Possible missing label or aria-label for <textarea>.'],
    ['resources/views/livewire/user/knowledge-base-chat.blade.php', 'icon_only_button_accessibility', 14, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/knowledge-base-chat.blade.php', 'icon_only_button_accessibility', 55, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/my-assets.blade.php', 'icon_only_button_accessibility', 208, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/my-payslips.blade.php', 'icon_only_button_accessibility', 16, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/my-payslips.blade.php', 'icon_only_button_accessibility', 21, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/my-payslips.blade.php', 'hardcoded_ui_text', 89, 'Possible hardcoded UI text: "Rp *********"'],
    ['resources/views/livewire/user/my-payslips.blade.php', 'icon_only_button_accessibility', 91, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/overtime-request.blade.php', 'icon_only_button_accessibility', 15, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/overtime-request.blade.php', 'icon_only_button_accessibility', 16, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/overtime-request.blade.php', 'icon_only_button_accessibility', 20, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/overtime-request.blade.php', 'icon_only_button_accessibility', 21, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/partials/team-attendance-corrections-history.blade.php', 'mobile_layout_red_flag', 2, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/partials/team-attendance-corrections-pending.blade.php', 'mobile_layout_red_flag', 2, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/partials/team-shift-swaps-history.blade.php', 'mobile_layout_red_flag', 2, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/partials/team-shift-swaps-pending.blade.php', 'mobile_layout_red_flag', 2, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/reimbursement-page.blade.php', 'icon_only_button_accessibility', 18, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/reimbursement-page.blade.php', 'hardcoded_ui_text', 248, 'Possible hardcoded UI text: "Rp"'],
    ['resources/views/livewire/user/reimbursement-page.blade.php', 'icon_only_button_accessibility', 24, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/reimbursement-page.blade.php', 'hardcoded_ui_text', 78, 'Possible hardcoded UI text: "Rp"'],
    ['resources/views/livewire/user/scan.blade.php', 'icon_only_button_accessibility', 402, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/scan.blade.php', 'icon_only_button_accessibility', 445, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/shift-swap-request-page.blade.php', 'icon_only_button_accessibility', 12, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/shift-swap-request-page.blade.php', 'mobile_layout_red_flag', 30, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/team-approvals-history.blade.php', 'mobile_layout_red_flag', 240, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/team-approvals-history.blade.php', 'mobile_layout_red_flag', 406, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/team-approvals-history.blade.php', 'mobile_layout_red_flag', 523, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/team-approvals-history.blade.php', 'hardcoded_ui_text', 601, 'Possible hardcoded UI text: "Rp"'],
    ['resources/views/livewire/user/team-approvals-history.blade.php', 'mobile_layout_red_flag', 63, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/team-approvals.blade.php', 'mobile_layout_red_flag', 292, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/team-approvals.blade.php', 'mobile_layout_red_flag', 505, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/team-approvals.blade.php', 'hardcoded_ui_text', 626, 'Possible hardcoded UI text: "SPL"'],
    ['resources/views/livewire/user/team-approvals.blade.php', 'mobile_layout_red_flag', 687, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/team-approvals.blade.php', 'mobile_layout_red_flag', 79, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/team-approvals.blade.php', 'hardcoded_ui_text', 810, 'Possible hardcoded UI text: "Rp"'],
    ['resources/views/navigation-menu.blade.php', 'icon_only_button_accessibility', 327, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/navigation-menu.blade.php', 'icon_only_button_accessibility', 405, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/profile/admin-show.blade.php', 'hardcoded_ui_text', 61, 'Possible hardcoded UI text: "ID"'],
    ['resources/views/profile/admin-show.blade.php', 'hardcoded_ui_text', 62, 'Possible hardcoded UI text: "EN"'],
    ['resources/views/profile/delete-user-form.blade.php', 'missing_form_label', 28, 'Possible missing label or aria-label for <input>.'],
    ['resources/views/profile/logout-other-browser-sessions-form.blade.php', 'missing_form_label', 66, 'Possible missing label or aria-label for <input>.'],
    ['resources/views/profile/show.blade.php', 'hardcoded_ui_text', 67, 'Possible hardcoded UI text: "ID"'],
    ['resources/views/profile/show.blade.php', 'hardcoded_ui_text', 68, 'Possible hardcoded UI text: "EN"'],
    ['resources/views/profile/two-factor-authentication-form.blade.php', 'mobile_layout_red_flag', 45, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/profile/update-profile-information-form.blade.php', 'icon_only_button_accessibility', 139, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/profile/update-profile-information-form.blade.php', 'icon_only_button_accessibility', 188, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/profile/update-profile-information-form.blade.php', 'icon_only_button_accessibility', 91, 'Possible icon-only button without aria-label or visible text.'],
];

return array_merge(
    array_map(
        static fn (string $file): array => [
            'file' => $file,
            'rule' => 'raw_inline_svg',
            'reason' => 'Custom SVG (brand logo / gauge chart) — bukan icon Heroicon, wajib raw.',
        ],
        $legacyInlineSvgFiles,
    ),
    array_map(
        static fn (array $finding): array => [
            'file' => $finding[0],
            'rule' => $finding[1],
            'key' => $finding[2].'|'.$finding[3],
            'reason' => 'Existing warning baseline; keep new UI warnings visible while legacy cleanup is tracked separately.',
        ],
        $legacyWarningFindings,
    ),
);
